# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(954, 630)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.parking_spots = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parking_spots.sizePolicy().hasHeightForWidth())
        self.parking_spots.setSizePolicy(sizePolicy)
        self.parking_spots.setMinimumSize(QtCore.QSize(0, 0))
        self.parking_spots.setStyleSheet("border-width: 3px;\n"
"border-style: solid;\n"
"border-color: white;\n"
"border-radius: 10px;")
        self.parking_spots.setObjectName("parking_spots")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.parking_spots)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.parking_spots)
        self.label_4.setStyleSheet("border-style: none;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.line_5 = QtWidgets.QFrame(self.parking_spots)
        self.line_5.setWindowModality(QtCore.Qt.NonModal)
        self.line_5.setMinimumSize(QtCore.QSize(0, 10))
        self.line_5.setBaseSize(QtCore.QSize(0, 0))
        self.line_5.setStyleSheet("background-color: rgb(252, 233, 79);\n"
"border-bottom-color:rgb(252, 233, 79);\n"
"border-top-color: rgb(252, 233, 79);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-radius: 5px;\n"
"")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.widget_3 = QtWidgets.QWidget(self.parking_spots)
        self.widget_3.setStyleSheet("border-width:0px;")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.parking_1 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parking_1.sizePolicy().hasHeightForWidth())
        self.parking_1.setSizePolicy(sizePolicy)
        self.parking_1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.parking_1.setAutoFillBackground(False)
        self.parking_1.setStyleSheet("background-color: rgba(55, 227, 28, 50%);\n"
"border-radius: 10px;\n"
"border-width: 1px;\n"
"\n"
"")
        self.parking_1.setObjectName("parking_1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.parking_1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.p1_lcd = QtWidgets.QLCDNumber(self.parking_1)
        self.p1_lcd.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1_lcd.sizePolicy().hasHeightForWidth())
        self.p1_lcd.setSizePolicy(sizePolicy)
        self.p1_lcd.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.p1_lcd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p1_lcd.setAutoFillBackground(False)
        self.p1_lcd.setStyleSheet("border-style: none;\n"
"border-color: none;\n"
"background-color: none;")
        self.p1_lcd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.p1_lcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.p1_lcd.setLineWidth(1)
        self.p1_lcd.setMidLineWidth(0)
        self.p1_lcd.setSmallDecimalPoint(False)
        self.p1_lcd.setDigitCount(1)
        self.p1_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.p1_lcd.setProperty("value", 1.0)
        self.p1_lcd.setProperty("intValue", 1)
        self.p1_lcd.setObjectName("p1_lcd")
        self.horizontalLayout_5.addWidget(self.p1_lcd)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.parking_1)
        self.line = QtWidgets.QFrame(self.widget_3)
        self.line.setWindowModality(QtCore.Qt.NonModal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(10, 0))
        self.line.setStyleSheet("background-color: rgb(252, 233, 79);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: rgb(252, 233, 79);\n"
"border-top-color: rgb(252, 233, 79);\n"
"border-bottom-left-radius:  5px;\n"
"border-bottom-right-radius: 5px;")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.parking_2 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parking_2.sizePolicy().hasHeightForWidth())
        self.parking_2.setSizePolicy(sizePolicy)
        self.parking_2.setStyleSheet("background-color: rgba(55, 227, 28, 50%);\n"
"border-radius: 10px;\n"
"border-width: 1px;\n"
"\n"
"")
        self.parking_2.setObjectName("parking_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.parking_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.p1_lcd_2 = QtWidgets.QLCDNumber(self.parking_2)
        self.p1_lcd_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1_lcd_2.sizePolicy().hasHeightForWidth())
        self.p1_lcd_2.setSizePolicy(sizePolicy)
        self.p1_lcd_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p1_lcd_2.setAutoFillBackground(False)
        self.p1_lcd_2.setStyleSheet("border-style: none;\n"
"border-color: none;\n"
"background-color: none;")
        self.p1_lcd_2.setFrameShape(QtWidgets.QFrame.Box)
        self.p1_lcd_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.p1_lcd_2.setLineWidth(0)
        self.p1_lcd_2.setMidLineWidth(0)
        self.p1_lcd_2.setSmallDecimalPoint(False)
        self.p1_lcd_2.setDigitCount(1)
        self.p1_lcd_2.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.p1_lcd_2.setProperty("value", 2.0)
        self.p1_lcd_2.setProperty("intValue", 2)
        self.p1_lcd_2.setObjectName("p1_lcd_2")
        self.horizontalLayout_6.addWidget(self.p1_lcd_2)
        spacerItem3 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_3.addWidget(self.parking_2)
        self.line_2 = QtWidgets.QFrame(self.widget_3)
        self.line_2.setMinimumSize(QtCore.QSize(10, 0))
        self.line_2.setStyleSheet("background-color: rgb(252, 233, 79);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: rgb(252, 233, 79);\n"
"border-top-color: rgb(252, 233, 79);\n"
"border-bottom-left-radius:  5px;\n"
"border-bottom-right-radius: 5px;")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        self.parking_3 = QtWidgets.QWidget(self.widget_3)
        self.parking_3.setStyleSheet("background-color: rgba(55, 227, 28, 50%);\n"
"border-radius: 10px;\n"
"border-width: 1px;\n"
"\n"
"")
        self.parking_3.setObjectName("parking_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.parking_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.p1_lcd_3 = QtWidgets.QLCDNumber(self.parking_3)
        self.p1_lcd_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1_lcd_3.sizePolicy().hasHeightForWidth())
        self.p1_lcd_3.setSizePolicy(sizePolicy)
        self.p1_lcd_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p1_lcd_3.setAutoFillBackground(False)
        self.p1_lcd_3.setStyleSheet("border-style: none;\n"
"border-color: none;\n"
"background-color: none;")
        self.p1_lcd_3.setFrameShape(QtWidgets.QFrame.Box)
        self.p1_lcd_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.p1_lcd_3.setLineWidth(0)
        self.p1_lcd_3.setMidLineWidth(0)
        self.p1_lcd_3.setSmallDecimalPoint(False)
        self.p1_lcd_3.setDigitCount(1)
        self.p1_lcd_3.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.p1_lcd_3.setProperty("value", 3.0)
        self.p1_lcd_3.setProperty("intValue", 3)
        self.p1_lcd_3.setObjectName("p1_lcd_3")
        self.horizontalLayout_2.addWidget(self.p1_lcd_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_3.addWidget(self.parking_3)
        self.line_3 = QtWidgets.QFrame(self.widget_3)
        self.line_3.setMinimumSize(QtCore.QSize(10, 0))
        self.line_3.setStyleSheet("background-color: rgb(252, 233, 79);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: rgb(252, 233, 79);\n"
"border-top-color: rgb(252, 233, 79);\n"
"border-bottom-left-radius:  5px;\n"
"border-bottom-right-radius: 5px;")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_3.addWidget(self.line_3)
        self.parking_4 = QtWidgets.QWidget(self.widget_3)
        self.parking_4.setStyleSheet("background-color: rgba(55, 227, 28, 50%);\n"
"border-radius: 10px;\n"
"border-width: 1px;\n"
"\n"
"")
        self.parking_4.setObjectName("parking_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.parking_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.p1_lcd_4 = QtWidgets.QLCDNumber(self.parking_4)
        self.p1_lcd_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1_lcd_4.sizePolicy().hasHeightForWidth())
        self.p1_lcd_4.setSizePolicy(sizePolicy)
        self.p1_lcd_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p1_lcd_4.setAutoFillBackground(False)
        self.p1_lcd_4.setStyleSheet("border-style: none;\n"
"border-color: none;\n"
"background-color: none;")
        self.p1_lcd_4.setFrameShape(QtWidgets.QFrame.Box)
        self.p1_lcd_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.p1_lcd_4.setLineWidth(0)
        self.p1_lcd_4.setMidLineWidth(0)
        self.p1_lcd_4.setSmallDecimalPoint(False)
        self.p1_lcd_4.setDigitCount(1)
        self.p1_lcd_4.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.p1_lcd_4.setProperty("value", 4.0)
        self.p1_lcd_4.setProperty("intValue", 4)
        self.p1_lcd_4.setObjectName("p1_lcd_4")
        self.horizontalLayout_7.addWidget(self.p1_lcd_4)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.horizontalLayout_3.addWidget(self.parking_4)
        self.line_4 = QtWidgets.QFrame(self.widget_3)
        self.line_4.setMinimumSize(QtCore.QSize(10, 0))
        self.line_4.setStyleSheet("background-color: rgb(252, 233, 79);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: rgb(252, 233, 79);\n"
"border-top-color: rgb(252, 233, 79);\n"
"border-bottom-left-radius:  5px;\n"
"border-bottom-right-radius: 5px;")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_3.addWidget(self.line_4)
        self.parking_5 = QtWidgets.QWidget(self.widget_3)
        self.parking_5.setStyleSheet("background-color: rgba(55, 227, 28, 50%);\n"
"border-radius: 10px;\n"
"border-width: 1px;\n"
"\n"
"")
        self.parking_5.setObjectName("parking_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.parking_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.p1_lcd_5 = QtWidgets.QLCDNumber(self.parking_5)
        self.p1_lcd_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1_lcd_5.sizePolicy().hasHeightForWidth())
        self.p1_lcd_5.setSizePolicy(sizePolicy)
        self.p1_lcd_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p1_lcd_5.setAutoFillBackground(False)
        self.p1_lcd_5.setStyleSheet("border-style: none;\n"
"border-color: none;\n"
"background-color: none;")
        self.p1_lcd_5.setFrameShape(QtWidgets.QFrame.Box)
        self.p1_lcd_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.p1_lcd_5.setLineWidth(0)
        self.p1_lcd_5.setMidLineWidth(0)
        self.p1_lcd_5.setSmallDecimalPoint(False)
        self.p1_lcd_5.setDigitCount(1)
        self.p1_lcd_5.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.p1_lcd_5.setProperty("value", 5.0)
        self.p1_lcd_5.setProperty("intValue", 5)
        self.p1_lcd_5.setObjectName("p1_lcd_5")
        self.horizontalLayout_8.addWidget(self.p1_lcd_5)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.horizontalLayout_3.addWidget(self.parking_5)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.parking_spots)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setStyleSheet("border-width: 3px;\n"
"border-color: white;\n"
"border-style: solid;\n"
"border-radius: 10px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setStyleSheet("border-radius: 5px;border-style: solid;border-color: white;border-width:1px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox = QtWidgets.QGroupBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setStyleSheet("border-width: 0px")
        self.groupBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(100, 100))
        self.frame_2.setMaximumSize(QtCore.QSize(200, 100))
        self.frame_2.setStyleSheet("border-radius: 5px;\n"
"border-style: solid;\n"
"border-color: white;\n"
"border-width:2px;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.warning_on_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warning_on_button.sizePolicy().hasHeightForWidth())
        self.warning_on_button.setSizePolicy(sizePolicy)
        self.warning_on_button.setMinimumSize(QtCore.QSize(50, 10))
        self.warning_on_button.setMaximumSize(QtCore.QSize(200, 50))
        self.warning_on_button.setStyleSheet("QPushButton::hover{background-color: rgb(32, 74, 135);}\n"
"QPushButton{background-color:rgb(222, 221, 218);}\n"
"QPushButton::checked{background-color:rgb(119, 118, 123);}")
        self.warning_on_button.setCheckable(False)
        self.warning_on_button.setAutoExclusive(True)
        self.warning_on_button.setObjectName("warning_on_button")
        self.horizontalLayout_4.addWidget(self.warning_on_button)
        self.warning_on_light = QtWidgets.QWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warning_on_light.sizePolicy().hasHeightForWidth())
        self.warning_on_light.setSizePolicy(sizePolicy)
        self.warning_on_light.setMinimumSize(QtCore.QSize(50, 50))
        self.warning_on_light.setMaximumSize(QtCore.QSize(100, 100))
        self.warning_on_light.setStyleSheet("background-color: rgba(0, 200, 0, 30%);\n"
"border-radius: 25px;")
        self.warning_on_light.setObjectName("warning_on_light")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.warning_on_light)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4.addWidget(self.warning_on_light, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_8.addWidget(self.frame_2)
        self.frame_31 = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_31.sizePolicy().hasHeightForWidth())
        self.frame_31.setSizePolicy(sizePolicy)
        self.frame_31.setMinimumSize(QtCore.QSize(100, 100))
        self.frame_31.setMaximumSize(QtCore.QSize(200, 100))
        self.frame_31.setStyleSheet("border-radius: 5px;\n"
"border-style: solid;\n"
"border-color: white;\n"
"border-width:2px;\n"
"")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.warning_off_button = QtWidgets.QPushButton(self.frame_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warning_off_button.sizePolicy().hasHeightForWidth())
        self.warning_off_button.setSizePolicy(sizePolicy)
        self.warning_off_button.setMinimumSize(QtCore.QSize(50, 10))
        self.warning_off_button.setMaximumSize(QtCore.QSize(200, 50))
        self.warning_off_button.setStyleSheet("QPushButton::hover{background-color: rgb(32, 74, 135);}\n"
"QPushButton{background-color:rgb(222, 221, 218);}\n"
"QPushButton::checked{background-color:rgb(119, 118, 123);}")
        self.warning_off_button.setCheckable(False)
        self.warning_off_button.setChecked(False)
        self.warning_off_button.setAutoExclusive(True)
        self.warning_off_button.setDefault(False)
        self.warning_off_button.setObjectName("warning_off_button")
        self.horizontalLayout_9.addWidget(self.warning_off_button)
        self.warning_off_light = QtWidgets.QWidget(self.frame_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warning_off_light.sizePolicy().hasHeightForWidth())
        self.warning_off_light.setSizePolicy(sizePolicy)
        self.warning_off_light.setMinimumSize(QtCore.QSize(50, 50))
        self.warning_off_light.setMaximumSize(QtCore.QSize(100, 100))
        self.warning_off_light.setStyleSheet("background-color: rgba(200, 0, 0, 80%);\n"
"border-radius: 25px;")
        self.warning_off_light.setObjectName("warning_off_light")
        self.horizontalLayout_9.addWidget(self.warning_off_light, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_8.addWidget(self.frame_31)
        self.warning_message_box = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warning_message_box.sizePolicy().hasHeightForWidth())
        self.warning_message_box.setSizePolicy(sizePolicy)
        self.warning_message_box.setStyleSheet("border-radius: 5px;\n"
"border-style: solid;\n"
"border-color: white;\n"
"border-width:2px;\n"
"background-color: white;\n"
"")
        self.warning_message_box.setText("")
        self.warning_message_box.setObjectName("warning_message_box")
        self.verticalLayout_8.addWidget(self.warning_message_box)
        self.horizontalLayout_10.addWidget(self.groupBox)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMaximumSize(QtCore.QSize(886, 16777215))
        self.frame_5.setStyleSheet("border-radius: 5px;\n"
"border-style: solid;\n"
"border-color: white;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setStyleSheet("border-width:0px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.temperature_textbox = QtWidgets.QLabel(self.frame_5)
        self.temperature_textbox.setStyleSheet("border-radius: 5px;\n"
"border-style: solid;\n"
"border-color: white;\n"
"border-width:2px;\n"
"background-color: white;\n"
"")
        self.temperature_textbox.setText("")
        self.temperature_textbox.setObjectName("temperature_textbox")
        self.verticalLayout_4.addWidget(self.temperature_textbox)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setStyleSheet("border-width:0px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.Display_Board_Message_Box = QtWidgets.QTextEdit(self.frame_5)
        self.Display_Board_Message_Box.setStyleSheet("border-radius: 5px;\n"
"border-style: solid;\n"
"border-color: white;\n"
"border-width:2px;\n"
"")
        self.Display_Board_Message_Box.setObjectName("Display_Board_Message_Box")
        self.verticalLayout_4.addWidget(self.Display_Board_Message_Box)
        self.SendDisplayMessage = QtWidgets.QPushButton(self.frame_5)
        self.SendDisplayMessage.setStyleSheet("QPushButton::hover{background-color: rgb(32, 74, 135);}\n"
"QPushButton{background-color:rgb(222, 221, 218);}\n"
"QPushButton::checked{background-color:rgb(119, 118, 123);}\n"
"QPushButton{border-radius:5px ; border-width: 1px; border-style: solid; border-color: white;}")
        self.SendDisplayMessage.setObjectName("SendDisplayMessage")
        self.verticalLayout_4.addWidget(self.SendDisplayMessage)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Parking Spots"))
        self.groupBox.setTitle(_translate("MainWindow", "Parking Lot Warning"))
        self.warning_on_button.setText(_translate("MainWindow", "Warning ON"))
        self.warning_off_button.setText(_translate("MainWindow", "Warning OFF"))
        self.label_2.setText(_translate("MainWindow", "Temperature"))
        self.label_3.setText(_translate("MainWindow", "Display Board Message"))
        self.SendDisplayMessage.setText(_translate("MainWindow", "Send Message"))
